### ISSUE TITLE
Markdownレンダリングを有効にしている場合に普通の絵文字とカスタム絵文字が連続するときに表示がズレる

### ISSUE THREAD

**Issue by mohemohe** [mstdn-plusminus-io/mastodon#109]
```css
.markdown-body p img {
   vertical-align: sub;
}
```

を追加する

```css
.markdown-body img[src*="/custom_emojis/images/"] {
    margin: 0 0 -4px!important;
}
```

を消す
