### ISSUE TITLE
最後のトゥートをホバーしたときのボタンが押せない

### ISSUE THREAD

**Issue by mohemohe** [mstdn-plusminus-io/mastodon#57]
![image](https://user-images.githubusercontent.com/5028163/156711440-16f97be5-ad3f-4582-9b5b-0232a8a8743a.png)

```css
.columns-area__panels__main > .columns-area .scrollable {
    padding-bottom: 48px !important;
}
```

とか
